"""initial schema

Revision ID: 333d0599a4d0
Revises: 
Create Date: 2026-06-06 22:42:17.447511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333d0599a4d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('cylinder_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacity_kg')
    )
    with op.batch_alter_table('cylinder_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cylinder_types_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'stock_manager', 'delivery_agent', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_number'), ['vehicle_number'], unique=True)

    op.create_table('customer_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_branches_branch_code'), ['branch_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_branches_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_branches_id'), ['id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_transit', 'completed', 'cancelled', name='deliverystatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_delivery_agent_id'), ['delivery_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_delivery_number'), ['delivery_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_type_id', sa.Integer(), nullable=False),
    sa.Column('full_quantity', sa.Integer(), nullable=False),
    sa.Column('empty_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_cylinder_type_id'), ['cylinder_type_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_id'), ['id'], unique=False)

    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cylinder_type_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'delivery_out', 'empty_return', 'refill', 'release', 'adjustment', name='stocktransactiontype'), nullable=False),
    sa.Column('full_change', sa.Integer(), nullable=False),
    sa.Column('empty_change', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_transactions_cylinder_type_id'), ['cylinder_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transactions_id'), ['id'], unique=False)

    op.create_table('delivery_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('previous_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('previous_agent_id', sa.Integer(), nullable=True),
    sa.Column('previous_date', sa.Date(), nullable=True),
    sa.Column('new_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('new_agent_id', sa.Integer(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['new_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['previous_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_assignment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_assignment_history_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignment_history_id'), ['id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_transit', 'completed', 'cancelled', name='deliverystatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['customer_branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('order_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('previous_delivery_id', sa.Integer(), nullable=True),
    sa.Column('new_delivery_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['previous_delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_assignment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_assignment_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_assignment_history_order_id'), ['order_id'], unique=False)

    op.create_table('order_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_evidences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_evidences_order_id'), ['order_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('cylinder_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_delivered', sa.Integer(), nullable=False),
    sa.Column('quantity_empty_collected', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('order_evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_evidences_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_evidences_id'))

    op.drop_table('order_evidences')
    with op.batch_alter_table('order_assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_assignment_history_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_assignment_history_id'))

    op.drop_table('order_assignment_history')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_branch_id'))

    op.drop_table('orders')
    with op.batch_alter_table('delivery_assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_assignment_history_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignment_history_delivery_id'))

    op.drop_table('delivery_assignment_history')
    with op.batch_alter_table('stock_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transactions_cylinder_type_id'))

    op.drop_table('stock_transactions')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_id'))
        batch_op.drop_index(batch_op.f('ix_stock_cylinder_type_id'))

    op.drop_table('stock')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_deliveries_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_deliveries_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivery_number'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivery_agent_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('customer_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_branches_id'))
        batch_op.drop_index(batch_op.f('ix_customer_branches_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_branches_branch_code'))

    op.drop_table('customer_branches')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('cylinder_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cylinder_types_id'))

    op.drop_table('cylinder_types')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_code'))

    op.drop_table('customers')
    # ### end Alembic commands ###
